### PR TITLE
Update Bob3 libraries

### PR DESCRIPTION
**Pull request by springob**
update of bob3-arduino-library files to most recent version

### CODE REVIEW

**Comment by VinArt** [comment]
Hi, I have tried pulling this and using it with the lab, but I get linker errors alike to his one:
```
undefined reference to `Bob3::getIRLight()'
undefined reference to `Bob3::setLed(unsigned char, unsigned int)'
```
we are using arduino-builder 1.4.4 and on my machine gcc 9.2.0 is installed. Should I use different versions of this software?

**Comment by springob** [comment]
Hi Artem,
can you post the full compiler/linker log?

**Comment by VinArt** [comment]
```
Linking everything together...
avr-gcc -w -Os -Wl,--gc-sections -mmcu=atmega88 -o /tmp/9uxvN--_W8U9/NEPOprog/target/NEPOprog.ino.elf /tmp/9uxvN--_W8U9/NEPOprog/target/sketch/NEPOprog.ino.cpp.o /tmp/9uxvN--_W8U9/NEPOprog/target/core/core.a -L/tmp/9uxvN--_W8U9/NEPOprog/target -lm
/usr/lib/gcc/avr/9.2.0/../../../../avr/bin/ld: /tmp/9uxvN--_W8U9/NEPOprog/target/sketch/NEPOprog.ino.cpp.o: in function `loop':
/tmp/9uxvN--_W8U9/NEPOprog/source/NEPOprog.ino:15: undefined reference to `Bob3::setLed(unsigned char, unsigned int)'
collect2: error: ld returned 1 exit status
Using library Bob3 in folder: /ora-cc-rsc/RobotArdu/libraries/Bob3 (legacy)
```

for sketch:

```
#include <math.h> 
#define _BOB3_INCLUDES
#include <BOB3.h> 
Bob3 rob;

void setup()
{
    
}

void loop()
{
    rob.setLed(EYE_2, RGB(0xFF, 0x00, 0x00));
}

```

Note that I put the RGB macro in the bob3.h, but when it is in a separate file the same behaviour occurs.

**Comment by VinArt** [comment]
So I tried more. There seems to be some issue with arduino builder. I managed to get this whole thing running ONLY when I copy files from bob3 direcory one level above to where BOB3.h resides and I had to comment out this block:

```
#ifdef ARDUINO

unsigned long millis() { return clock_get_sys_ms(); }
unsigned long micros() { return clock_get_sys_us(); }
void delay(unsigned long ms) { clock_sleep_ms(ms); }
void _time_suspend() {}
void _time_resume() {}

#endif
```

in clock.c, otherwise the compiler complains about re-definition of functions.

**Comment by springob** [comment]
OK I will setup a toolchain with arduino-builder 1.4.4, and have a look...
(the clock functions are essential for correct timing, otherwise interrupts will have massive impact)

**Comment by boonto** [comment]
Already merged in another way by @VinArt.

**Pull request closed without merging**
